# Generated by Django 4.0.3 on 2022-03-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('site_url', models.URLField()),
                ('products_tag', models.CharField(max_length=16)),
                ('products_class', models.CharField(max_length=255)),
                ('title_tag', models.CharField(max_length=16)),
                ('title_class', models.CharField(max_length=255)),
                ('url_tag', models.CharField(max_length=16)),
                ('url_class', models.CharField(max_length=255)),
                ('url_attr', models.CharField(max_length=16)),
                ('price_tag', models.CharField(max_length=16)),
                ('price_class', models.CharField(max_length=255)),
                ('price_contents', models.IntegerField()),
            ],
        ),
    ]
